// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: intellisphere/v1/intellisphere.proto

package intellispherev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LLMCore_Complete_FullMethodName       = "/intellisphere.v1.LLMCore/Complete"
	LLMCore_CompleteStream_FullMethodName = "/intellisphere.v1.LLMCore/CompleteStream"
	LLMCore_Health_FullMethodName         = "/intellisphere.v1.LLMCore/Health"
)

// LLMCoreClient is the client API for LLMCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LLMCore is the service that proxies requests to LLM providers.
// Sphere connects to Core over gRPC on the internal network.
type LLMCoreClient interface {
	// Complete sends a completion request and returns a single response.
	Complete(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error)
	// CompleteStream sends a completion request and returns a stream of chunks.
	CompleteStream(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompletionChunk], error)
	// Health checks the Core's readiness including LLM provider connectivity.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type lLMCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMCoreClient(cc grpc.ClientConnInterface) LLMCoreClient {
	return &lLMCoreClient{cc}
}

func (c *lLMCoreClient) Complete(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompletionResponse)
	err := c.cc.Invoke(ctx, LLMCore_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMCoreClient) CompleteStream(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompletionChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LLMCore_ServiceDesc.Streams[0], LLMCore_CompleteStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CompletionRequest, CompletionChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMCore_CompleteStreamClient = grpc.ServerStreamingClient[CompletionChunk]

func (c *lLMCoreClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, LLMCore_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMCoreServer is the server API for LLMCore service.
// All implementations must embed UnimplementedLLMCoreServer
// for forward compatibility.
//
// LLMCore is the service that proxies requests to LLM providers.
// Sphere connects to Core over gRPC on the internal network.
type LLMCoreServer interface {
	// Complete sends a completion request and returns a single response.
	Complete(context.Context, *CompletionRequest) (*CompletionResponse, error)
	// CompleteStream sends a completion request and returns a stream of chunks.
	CompleteStream(*CompletionRequest, grpc.ServerStreamingServer[CompletionChunk]) error
	// Health checks the Core's readiness including LLM provider connectivity.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedLLMCoreServer()
}

// UnimplementedLLMCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMCoreServer struct{}

func (UnimplementedLLMCoreServer) Complete(context.Context, *CompletionRequest) (*CompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedLLMCoreServer) CompleteStream(*CompletionRequest, grpc.ServerStreamingServer[CompletionChunk]) error {
	return status.Error(codes.Unimplemented, "method CompleteStream not implemented")
}
func (UnimplementedLLMCoreServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLLMCoreServer) mustEmbedUnimplementedLLMCoreServer() {}
func (UnimplementedLLMCoreServer) testEmbeddedByValue()                 {}

// UnsafeLLMCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMCoreServer will
// result in compilation errors.
type UnsafeLLMCoreServer interface {
	mustEmbedUnimplementedLLMCoreServer()
}

func RegisterLLMCoreServer(s grpc.ServiceRegistrar, srv LLMCoreServer) {
	// If the following call panics, it indicates UnimplementedLLMCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMCore_ServiceDesc, srv)
}

func _LLMCore_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMCoreServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMCore_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMCoreServer).Complete(ctx, req.(*CompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMCore_CompleteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LLMCoreServer).CompleteStream(m, &grpc.GenericServerStream[CompletionRequest, CompletionChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMCore_CompleteStreamServer = grpc.ServerStreamingServer[CompletionChunk]

func _LLMCore_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMCoreServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMCore_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMCoreServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMCore_ServiceDesc is the grpc.ServiceDesc for LLMCore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMCore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "intellisphere.v1.LLMCore",
	HandlerType: (*LLMCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Complete",
			Handler:    _LLMCore_Complete_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _LLMCore_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CompleteStream",
			Handler:       _LLMCore_CompleteStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "intellisphere/v1/intellisphere.proto",
}
