// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: intellisphere/v1/intellisphere.proto

package intellispherev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkType int32

const (
	ChunkType_CHUNK_TYPE_UNSPECIFIED     ChunkType = 0
	ChunkType_CHUNK_TYPE_TEXT_DELTA      ChunkType = 1
	ChunkType_CHUNK_TYPE_TOOL_CALL_START ChunkType = 2
	ChunkType_CHUNK_TYPE_TOOL_CALL_DELTA ChunkType = 3
	ChunkType_CHUNK_TYPE_TOOL_CALL_END   ChunkType = 4
	ChunkType_CHUNK_TYPE_MESSAGE_END     ChunkType = 5
)

// Enum value maps for ChunkType.
var (
	ChunkType_name = map[int32]string{
		0: "CHUNK_TYPE_UNSPECIFIED",
		1: "CHUNK_TYPE_TEXT_DELTA",
		2: "CHUNK_TYPE_TOOL_CALL_START",
		3: "CHUNK_TYPE_TOOL_CALL_DELTA",
		4: "CHUNK_TYPE_TOOL_CALL_END",
		5: "CHUNK_TYPE_MESSAGE_END",
	}
	ChunkType_value = map[string]int32{
		"CHUNK_TYPE_UNSPECIFIED":     0,
		"CHUNK_TYPE_TEXT_DELTA":      1,
		"CHUNK_TYPE_TOOL_CALL_START": 2,
		"CHUNK_TYPE_TOOL_CALL_DELTA": 3,
		"CHUNK_TYPE_TOOL_CALL_END":   4,
		"CHUNK_TYPE_MESSAGE_END":     5,
	}
)

func (x ChunkType) Enum() *ChunkType {
	p := new(ChunkType)
	*p = x
	return p
}

func (x ChunkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkType) Descriptor() protoreflect.EnumDescriptor {
	return file_intellisphere_v1_intellisphere_proto_enumTypes[0].Descriptor()
}

func (ChunkType) Type() protoreflect.EnumType {
	return &file_intellisphere_v1_intellisphere_proto_enumTypes[0]
}

func (x ChunkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChunkType.Descriptor instead.
func (ChunkType) EnumDescriptor() ([]byte, []int) {
	return file_intellisphere_v1_intellisphere_proto_rawDescGZIP(), []int{0}
}

type StopReason int32

const (
	StopReason_STOP_REASON_UNSPECIFIED   StopReason = 0
	StopReason_STOP_REASON_END_TURN      StopReason = 1
	StopReason_STOP_REASON_TOOL_USE      StopReason = 2
	StopReason_STOP_REASON_MAX_TOKENS    StopReason = 3
	StopReason_STOP_REASON_STOP_SEQUENCE StopReason = 4
)

// Enum value maps for StopReason.
var (
	StopReason_name = map[int32]string{
		0: "STOP_REASON_UNSPECIFIED",
		1: "STOP_REASON_END_TURN",
		2: "STOP_REASON_TOOL_USE",
		3: "STOP_REASON_MAX_TOKENS",
		4: "STOP_REASON_STOP_SEQUENCE",
	}
	StopReason_value = map[string]int32{
		"STOP_REASON_UNSPECIFIED":   0,
		"STOP_REASON_END_TURN":      1,
		"STOP_REASON_TOOL_USE":      2,
		"STOP_REASON_MAX_TOKENS":    3,
		"STOP_REASON_STOP_SEQUENCE": 4,
	}
)

func (x StopReason) Enum() *StopReason {
	p := new(StopReason)
	*p = x
	return p
}

func (x StopReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StopReason) Descriptor() protoreflect.EnumDescriptor {
	return file_intellisphere_v1_intellisphere_proto_enumTypes[1].Descriptor()
}

func (StopReason) Type() protoreflect.EnumType {
	return &file_intellisphere_v1_intellisphere_proto_enumTypes[1]
}

func (x StopReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StopReason.Descriptor instead.
func (StopReason) EnumDescriptor() ([]byte, []int) {
	return file_intellisphere_v1_intellisphere_proto_rawDescGZIP(), []int{1}
}

type CompletionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The LLM provider to use (e.g., "anthropic", "openai").
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Model identifier (e.g., "claude-sonnet-4-20250514").
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// System prompt. Sphere injects tool definitions here.
	System string `protobuf:"bytes,3,opt,name=system,proto3" json:"system,omitempty"`
	// Conversation messages.
	Messages []*Message `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	// Maximum tokens to generate.
	MaxTokens int32 `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// Temperature (0.0 to 1.0).
	Temperature float32 `protobuf:"fixed32,6,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// Tool definitions available to the model.
	Tools []*ToolDefinition `protobuf:"bytes,7,rep,name=tools,proto3" json:"tools,omitempty"`
	// Optional stop sequences.
	StopSequences []string `protobuf:"bytes,8,rep,name=stop_sequences,json=stopSequences,proto3" json:"stop_sequences,omitempty"`
	// Request metadata for tracing.
	Metadata      *RequestMetadata `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionRequest) Reset() {
	*x = CompletionRequest{}
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionRequest) ProtoMessage() {}

func (x *CompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionRequest.ProtoReflect.Descriptor instead.
func (*CompletionRequest) Descriptor() ([]byte, []int) {
	return file_intellisphere_v1_intellisphere_proto_rawDescGZIP(), []int{0}
}

func (x *CompletionRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompletionRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *CompletionRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CompletionRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *CompletionRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *CompletionRequest) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *CompletionRequest) GetStopSequences() []string {
	if x != nil {
		return x.StopSequences
	}
	return nil
}

func (x *CompletionRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Role: "user", "assistant", or "tool_result".
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// Text content of the message.
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Tool call results (when role = "tool_result").
	ToolResults []*ToolResult `protobuf:"bytes,3,rep,name=tool_results,json=toolResults,proto3" json:"tool_results,omitempty"`
	// Tool calls made by the assistant (populated in responses).
	ToolCalls     []*ToolCall `protobuf:"bytes,4,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_intellisphere_v1_intellisphere_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetToolResults() []*ToolResult {
	if x != nil {
		return x.ToolResults
	}
	return nil
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type ToolDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique tool name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable description for the LLM.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// JSON Schema defining the tool's input parameters.
	InputSchemaJson string `protobuf:"bytes,3,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_intellisphere_v1_intellisphere_proto_rawDescGZIP(), []int{2}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetInputSchemaJson() string {
	if x != nil {
		return x.InputSchemaJson
	}
	return ""
}

type ToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this tool call.
	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Name of the tool to invoke.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// JSON-encoded arguments.
	ArgumentsJson string `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_intellisphere_v1_intellisphere_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCall) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

type ToolResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The call_id this result corresponds to.
	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// JSON-encoded result.
	ResultJson string `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	// Whether this result represents an error.
	IsError       bool `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_intellisphere_v1_intellisphere_proto_rawDescGZIP(), []int{4}
}

func (x *ToolResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResult) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type CompletionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The assistant's response content.
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// Tool calls requested by the model.
	ToolCalls []*ToolCall `protobuf:"bytes,2,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	// Why the model stopped generating.
	StopReason StopReason `protobuf:"varint,3,opt,name=stop_reason,json=stopReason,proto3,enum=intellisphere.v1.StopReason" json:"stop_reason,omitempty"`
	// Token usage for this completion.
	Usage *Usage `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	// Model that actually served the request.
	Model         string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionResponse) Reset() {
	*x = CompletionResponse{}
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionResponse) ProtoMessage() {}

func (x *CompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionResponse.ProtoReflect.Descriptor instead.
func (*CompletionResponse) Descriptor() ([]byte, []int) {
	return file_intellisphere_v1_intellisphere_proto_rawDescGZIP(), []int{5}
}

func (x *CompletionResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CompletionResponse) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *CompletionResponse) GetStopReason() StopReason {
	if x != nil {
		return x.StopReason
	}
	return StopReason_STOP_REASON_UNSPECIFIED
}

func (x *CompletionResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *CompletionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type CompletionChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Incremental text content.
	Delta string `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	// Tool call being streamed (partial).
	ToolCall *ToolCall `protobuf:"bytes,2,opt,name=tool_call,json=toolCall,proto3" json:"tool_call,omitempty"`
	// Set on the final chunk.
	StopReason StopReason `protobuf:"varint,3,opt,name=stop_reason,json=stopReason,proto3,enum=intellisphere.v1.StopReason" json:"stop_reason,omitempty"`
	// Set on the final chunk.
	Usage *Usage `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	// Chunk type for client routing.
	ChunkType     ChunkType `protobuf:"varint,5,opt,name=chunk_type,json=chunkType,proto3,enum=intellisphere.v1.ChunkType" json:"chunk_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionChunk) Reset() {
	*x = CompletionChunk{}
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionChunk) ProtoMessage() {}

func (x *CompletionChunk) ProtoReflect() protoreflect.Message {
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionChunk.ProtoReflect.Descriptor instead.
func (*CompletionChunk) Descriptor() ([]byte, []int) {
	return file_intellisphere_v1_intellisphere_proto_rawDescGZIP(), []int{6}
}

func (x *CompletionChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *CompletionChunk) GetToolCall() *ToolCall {
	if x != nil {
		return x.ToolCall
	}
	return nil
}

func (x *CompletionChunk) GetStopReason() StopReason {
	if x != nil {
		return x.StopReason
	}
	return StopReason_STOP_REASON_UNSPECIFIED
}

func (x *CompletionChunk) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *CompletionChunk) GetChunkType() ChunkType {
	if x != nil {
		return x.ChunkType
	}
	return ChunkType_CHUNK_TYPE_UNSPECIFIED
}

type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_intellisphere_v1_intellisphere_proto_rawDescGZIP(), []int{7}
}

func (x *Usage) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

type RequestMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request ID for tracing.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Session ID for multi-turn conversations.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Timestamp of the request.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMetadata) Reset() {
	*x = RequestMetadata{}
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetadata) ProtoMessage() {}

func (x *RequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetadata.ProtoReflect.Descriptor instead.
func (*RequestMetadata) Descriptor() ([]byte, []int) {
	return file_intellisphere_v1_intellisphere_proto_rawDescGZIP(), []int{8}
}

func (x *RequestMetadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestMetadata) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RequestMetadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_intellisphere_v1_intellisphere_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_intellisphere_v1_intellisphere_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_intellisphere_v1_intellisphere_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_intellisphere_v1_intellisphere_proto protoreflect.FileDescriptor

const file_intellisphere_v1_intellisphere_proto_rawDesc = "" +
	"\n" +
	"$intellisphere/v1/intellisphere.proto\x12\x10intellisphere.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf3\x02\n" +
	"\x11CompletionRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06system\x18\x03 \x01(\tR\x06system\x125\n" +
	"\bmessages\x18\x04 \x03(\v2\x19.intellisphere.v1.MessageR\bmessages\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x06 \x01(\x02R\vtemperature\x126\n" +
	"\x05tools\x18\a \x03(\v2 .intellisphere.v1.ToolDefinitionR\x05tools\x12%\n" +
	"\x0estop_sequences\x18\b \x03(\tR\rstopSequences\x12=\n" +
	"\bmetadata\x18\t \x01(\v2!.intellisphere.v1.RequestMetadataR\bmetadata\"\xb3\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12?\n" +
	"\ftool_results\x18\x03 \x03(\v2\x1c.intellisphere.v1.ToolResultR\vtoolResults\x129\n" +
	"\n" +
	"tool_calls\x18\x04 \x03(\v2\x1a.intellisphere.v1.ToolCallR\ttoolCalls\"r\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11input_schema_json\x18\x03 \x01(\tR\x0finputSchemaJson\"^\n" +
	"\bToolCall\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\"a\n" +
	"\n" +
	"ToolResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\"\xed\x01\n" +
	"\x12CompletionResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x129\n" +
	"\n" +
	"tool_calls\x18\x02 \x03(\v2\x1a.intellisphere.v1.ToolCallR\ttoolCalls\x12=\n" +
	"\vstop_reason\x18\x03 \x01(\x0e2\x1c.intellisphere.v1.StopReasonR\n" +
	"stopReason\x12-\n" +
	"\x05usage\x18\x04 \x01(\v2\x17.intellisphere.v1.UsageR\x05usage\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"\x8a\x02\n" +
	"\x0fCompletionChunk\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x127\n" +
	"\ttool_call\x18\x02 \x01(\v2\x1a.intellisphere.v1.ToolCallR\btoolCall\x12=\n" +
	"\vstop_reason\x18\x03 \x01(\x0e2\x1c.intellisphere.v1.StopReasonR\n" +
	"stopReason\x12-\n" +
	"\x05usage\x18\x04 \x01(\v2\x17.intellisphere.v1.UsageR\x05usage\x12:\n" +
	"\n" +
	"chunk_type\x18\x05 \x01(\x0e2\x1b.intellisphere.v1.ChunkTypeR\tchunkType\"O\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\"\x89\x01\n" +
	"\x0fRequestMetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x0f\n" +
	"\rHealthRequest\"`\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*\xbc\x01\n" +
	"\tChunkType\x12\x1a\n" +
	"\x16CHUNK_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CHUNK_TYPE_TEXT_DELTA\x10\x01\x12\x1e\n" +
	"\x1aCHUNK_TYPE_TOOL_CALL_START\x10\x02\x12\x1e\n" +
	"\x1aCHUNK_TYPE_TOOL_CALL_DELTA\x10\x03\x12\x1c\n" +
	"\x18CHUNK_TYPE_TOOL_CALL_END\x10\x04\x12\x1a\n" +
	"\x16CHUNK_TYPE_MESSAGE_END\x10\x05*\x98\x01\n" +
	"\n" +
	"StopReason\x12\x1b\n" +
	"\x17STOP_REASON_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14STOP_REASON_END_TURN\x10\x01\x12\x18\n" +
	"\x14STOP_REASON_TOOL_USE\x10\x02\x12\x1a\n" +
	"\x16STOP_REASON_MAX_TOKENS\x10\x03\x12\x1d\n" +
	"\x19STOP_REASON_STOP_SEQUENCE\x10\x042\x89\x02\n" +
	"\aLLMCore\x12U\n" +
	"\bComplete\x12#.intellisphere.v1.CompletionRequest\x1a$.intellisphere.v1.CompletionResponse\x12Z\n" +
	"\x0eCompleteStream\x12#.intellisphere.v1.CompletionRequest\x1a!.intellisphere.v1.CompletionChunk0\x01\x12K\n" +
	"\x06Health\x12\x1f.intellisphere.v1.HealthRequest\x1a .intellisphere.v1.HealthResponseB\"Z intellisphere/v1;intellispherev1b\x06proto3"

var (
	file_intellisphere_v1_intellisphere_proto_rawDescOnce sync.Once
	file_intellisphere_v1_intellisphere_proto_rawDescData []byte
)

func file_intellisphere_v1_intellisphere_proto_rawDescGZIP() []byte {
	file_intellisphere_v1_intellisphere_proto_rawDescOnce.Do(func() {
		file_intellisphere_v1_intellisphere_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_intellisphere_v1_intellisphere_proto_rawDesc), len(file_intellisphere_v1_intellisphere_proto_rawDesc)))
	})
	return file_intellisphere_v1_intellisphere_proto_rawDescData
}

var file_intellisphere_v1_intellisphere_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_intellisphere_v1_intellisphere_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_intellisphere_v1_intellisphere_proto_goTypes = []any{
	(ChunkType)(0),                // 0: intellisphere.v1.ChunkType
	(StopReason)(0),               // 1: intellisphere.v1.StopReason
	(*CompletionRequest)(nil),     // 2: intellisphere.v1.CompletionRequest
	(*Message)(nil),               // 3: intellisphere.v1.Message
	(*ToolDefinition)(nil),        // 4: intellisphere.v1.ToolDefinition
	(*ToolCall)(nil),              // 5: intellisphere.v1.ToolCall
	(*ToolResult)(nil),            // 6: intellisphere.v1.ToolResult
	(*CompletionResponse)(nil),    // 7: intellisphere.v1.CompletionResponse
	(*CompletionChunk)(nil),       // 8: intellisphere.v1.CompletionChunk
	(*Usage)(nil),                 // 9: intellisphere.v1.Usage
	(*RequestMetadata)(nil),       // 10: intellisphere.v1.RequestMetadata
	(*HealthRequest)(nil),         // 11: intellisphere.v1.HealthRequest
	(*HealthResponse)(nil),        // 12: intellisphere.v1.HealthResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_intellisphere_v1_intellisphere_proto_depIdxs = []int32{
	3,  // 0: intellisphere.v1.CompletionRequest.messages:type_name -> intellisphere.v1.Message
	4,  // 1: intellisphere.v1.CompletionRequest.tools:type_name -> intellisphere.v1.ToolDefinition
	10, // 2: intellisphere.v1.CompletionRequest.metadata:type_name -> intellisphere.v1.RequestMetadata
	6,  // 3: intellisphere.v1.Message.tool_results:type_name -> intellisphere.v1.ToolResult
	5,  // 4: intellisphere.v1.Message.tool_calls:type_name -> intellisphere.v1.ToolCall
	5,  // 5: intellisphere.v1.CompletionResponse.tool_calls:type_name -> intellisphere.v1.ToolCall
	1,  // 6: intellisphere.v1.CompletionResponse.stop_reason:type_name -> intellisphere.v1.StopReason
	9,  // 7: intellisphere.v1.CompletionResponse.usage:type_name -> intellisphere.v1.Usage
	5,  // 8: intellisphere.v1.CompletionChunk.tool_call:type_name -> intellisphere.v1.ToolCall
	1,  // 9: intellisphere.v1.CompletionChunk.stop_reason:type_name -> intellisphere.v1.StopReason
	9,  // 10: intellisphere.v1.CompletionChunk.usage:type_name -> intellisphere.v1.Usage
	0,  // 11: intellisphere.v1.CompletionChunk.chunk_type:type_name -> intellisphere.v1.ChunkType
	13, // 12: intellisphere.v1.RequestMetadata.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 13: intellisphere.v1.LLMCore.Complete:input_type -> intellisphere.v1.CompletionRequest
	2,  // 14: intellisphere.v1.LLMCore.CompleteStream:input_type -> intellisphere.v1.CompletionRequest
	11, // 15: intellisphere.v1.LLMCore.Health:input_type -> intellisphere.v1.HealthRequest
	7,  // 16: intellisphere.v1.LLMCore.Complete:output_type -> intellisphere.v1.CompletionResponse
	8,  // 17: intellisphere.v1.LLMCore.CompleteStream:output_type -> intellisphere.v1.CompletionChunk
	12, // 18: intellisphere.v1.LLMCore.Health:output_type -> intellisphere.v1.HealthResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_intellisphere_v1_intellisphere_proto_init() }
func file_intellisphere_v1_intellisphere_proto_init() {
	if File_intellisphere_v1_intellisphere_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_intellisphere_v1_intellisphere_proto_rawDesc), len(file_intellisphere_v1_intellisphere_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_intellisphere_v1_intellisphere_proto_goTypes,
		DependencyIndexes: file_intellisphere_v1_intellisphere_proto_depIdxs,
		EnumInfos:         file_intellisphere_v1_intellisphere_proto_enumTypes,
		MessageInfos:      file_intellisphere_v1_intellisphere_proto_msgTypes,
	}.Build()
	File_intellisphere_v1_intellisphere_proto = out.File
	file_intellisphere_v1_intellisphere_proto_goTypes = nil
	file_intellisphere_v1_intellisphere_proto_depIdxs = nil
}
