// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompletionRequest {
    /// The LLM provider to use (e.g., "anthropic", "openai").
    #[prost(string, tag = "1")]
    pub provider: ::prost::alloc::string::String,
    /// Model identifier (e.g., "claude-sonnet-4-20250514").
    #[prost(string, tag = "2")]
    pub model: ::prost::alloc::string::String,
    /// System prompt. Sphere injects tool definitions here.
    #[prost(string, tag = "3")]
    pub system: ::prost::alloc::string::String,
    /// Conversation messages.
    #[prost(message, repeated, tag = "4")]
    pub messages: ::prost::alloc::vec::Vec<Message>,
    /// Maximum tokens to generate.
    #[prost(int32, tag = "5")]
    pub max_tokens: i32,
    /// Temperature (0.0 to 1.0).
    #[prost(float, tag = "6")]
    pub temperature: f32,
    /// Tool definitions available to the model.
    #[prost(message, repeated, tag = "7")]
    pub tools: ::prost::alloc::vec::Vec<ToolDefinition>,
    /// Optional stop sequences.
    #[prost(string, repeated, tag = "8")]
    pub stop_sequences: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Request metadata for tracing.
    #[prost(message, optional, tag = "9")]
    pub metadata: ::core::option::Option<RequestMetadata>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    /// Role: "user", "assistant", or "tool_result".
    #[prost(string, tag = "1")]
    pub role: ::prost::alloc::string::String,
    /// Text content of the message.
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    /// Tool call results (when role = "tool_result").
    #[prost(message, repeated, tag = "3")]
    pub tool_results: ::prost::alloc::vec::Vec<ToolResult>,
    /// Tool calls made by the assistant (populated in responses).
    #[prost(message, repeated, tag = "4")]
    pub tool_calls: ::prost::alloc::vec::Vec<ToolCall>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolDefinition {
    /// Unique tool name.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Human-readable description for the LLM.
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    /// JSON Schema defining the tool's input parameters.
    #[prost(string, tag = "3")]
    pub input_schema_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolCall {
    /// Unique identifier for this tool call.
    #[prost(string, tag = "1")]
    pub call_id: ::prost::alloc::string::String,
    /// Name of the tool to invoke.
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// JSON-encoded arguments.
    #[prost(string, tag = "3")]
    pub arguments_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolResult {
    /// The call_id this result corresponds to.
    #[prost(string, tag = "1")]
    pub call_id: ::prost::alloc::string::String,
    /// JSON-encoded result.
    #[prost(string, tag = "2")]
    pub result_json: ::prost::alloc::string::String,
    /// Whether this result represents an error.
    #[prost(bool, tag = "3")]
    pub is_error: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompletionResponse {
    /// The assistant's response content.
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
    /// Tool calls requested by the model.
    #[prost(message, repeated, tag = "2")]
    pub tool_calls: ::prost::alloc::vec::Vec<ToolCall>,
    /// Why the model stopped generating.
    #[prost(enumeration = "StopReason", tag = "3")]
    pub stop_reason: i32,
    /// Token usage for this completion.
    #[prost(message, optional, tag = "4")]
    pub usage: ::core::option::Option<Usage>,
    /// Model that actually served the request.
    #[prost(string, tag = "5")]
    pub model: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompletionChunk {
    /// Incremental text content.
    #[prost(string, tag = "1")]
    pub delta: ::prost::alloc::string::String,
    /// Tool call being streamed (partial).
    #[prost(message, optional, tag = "2")]
    pub tool_call: ::core::option::Option<ToolCall>,
    /// Set on the final chunk.
    #[prost(enumeration = "StopReason", tag = "3")]
    pub stop_reason: i32,
    /// Set on the final chunk.
    #[prost(message, optional, tag = "4")]
    pub usage: ::core::option::Option<Usage>,
    /// Chunk type for client routing.
    #[prost(enumeration = "ChunkType", tag = "5")]
    pub chunk_type: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Usage {
    #[prost(int32, tag = "1")]
    pub input_tokens: i32,
    #[prost(int32, tag = "2")]
    pub output_tokens: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestMetadata {
    /// Unique request ID for tracing.
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// Session ID for multi-turn conversations.
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    /// Timestamp of the request.
    #[prost(message, optional, tag = "3")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthResponse {
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    #[prost(string, tag = "2")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ChunkType {
    Unspecified = 0,
    TextDelta = 1,
    ToolCallStart = 2,
    ToolCallDelta = 3,
    ToolCallEnd = 4,
    MessageEnd = 5,
}
impl ChunkType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CHUNK_TYPE_UNSPECIFIED",
            Self::TextDelta => "CHUNK_TYPE_TEXT_DELTA",
            Self::ToolCallStart => "CHUNK_TYPE_TOOL_CALL_START",
            Self::ToolCallDelta => "CHUNK_TYPE_TOOL_CALL_DELTA",
            Self::ToolCallEnd => "CHUNK_TYPE_TOOL_CALL_END",
            Self::MessageEnd => "CHUNK_TYPE_MESSAGE_END",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CHUNK_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CHUNK_TYPE_TEXT_DELTA" => Some(Self::TextDelta),
            "CHUNK_TYPE_TOOL_CALL_START" => Some(Self::ToolCallStart),
            "CHUNK_TYPE_TOOL_CALL_DELTA" => Some(Self::ToolCallDelta),
            "CHUNK_TYPE_TOOL_CALL_END" => Some(Self::ToolCallEnd),
            "CHUNK_TYPE_MESSAGE_END" => Some(Self::MessageEnd),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StopReason {
    Unspecified = 0,
    EndTurn = 1,
    ToolUse = 2,
    MaxTokens = 3,
    StopSequence = 4,
}
impl StopReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STOP_REASON_UNSPECIFIED",
            Self::EndTurn => "STOP_REASON_END_TURN",
            Self::ToolUse => "STOP_REASON_TOOL_USE",
            Self::MaxTokens => "STOP_REASON_MAX_TOKENS",
            Self::StopSequence => "STOP_REASON_STOP_SEQUENCE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STOP_REASON_UNSPECIFIED" => Some(Self::Unspecified),
            "STOP_REASON_END_TURN" => Some(Self::EndTurn),
            "STOP_REASON_TOOL_USE" => Some(Self::ToolUse),
            "STOP_REASON_MAX_TOKENS" => Some(Self::MaxTokens),
            "STOP_REASON_STOP_SEQUENCE" => Some(Self::StopSequence),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod llm_core_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// LLMCore is the service that proxies requests to LLM providers.
    /// Sphere connects to Core over gRPC on the internal network.
    #[derive(Debug, Clone)]
    pub struct LlmCoreClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl LlmCoreClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> LlmCoreClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> LlmCoreClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            LlmCoreClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Complete sends a completion request and returns a single response.
        pub async fn complete(
            &mut self,
            request: impl tonic::IntoRequest<super::CompletionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CompletionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/intellisphere.v1.LLMCore/Complete",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("intellisphere.v1.LLMCore", "Complete"));
            self.inner.unary(req, path, codec).await
        }
        /// CompleteStream sends a completion request and returns a stream of chunks.
        pub async fn complete_stream(
            &mut self,
            request: impl tonic::IntoRequest<super::CompletionRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::CompletionChunk>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/intellisphere.v1.LLMCore/CompleteStream",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("intellisphere.v1.LLMCore", "CompleteStream"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Health checks the Core's readiness including LLM provider connectivity.
        pub async fn health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/intellisphere.v1.LLMCore/Health",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("intellisphere.v1.LLMCore", "Health"));
            self.inner.unary(req, path, codec).await
        }
    }
}
